// Mock car data
export const cars = [
  {
    id: "1",
    name: "Tesla Model S",
    brand: "Tesla",
    price: 89990,
    fuelType: "Electric",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: "NA",
    power: 670,
    description:
      "The Tesla Model S is an all-electric five-door liftback sedan produced by Tesla, Inc. The Model S features a dual-motor, all-wheel drive layout.",
    specifications: {
      range: "405 miles",
      acceleration: "1.99s 0-60 mph",
      top_speed: "200 mph",
      drive: "All-Wheel Drive",
      peak_power: "1,020 hp",
      wheels: '19" or 21"',
      weight: "4,561 lbs",
      cargo: "28 cu ft",
    },
  },
  {
    id: "2",
    name: "BMW 3 Series",
    brand: "BMW",
    price: 41450,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 15.5,
    power: 255,
    description:
      "The BMW 3 Series is a line of compact executive cars manufactured by the German automaker BMW since May 1975. It is the successor to the 02 Series and has been produced in seven generations.",
    specifications: {
      engine: "2.0L 4-Cylinder Turbo",
      transmission: "8-Speed Automatic",
      drive: "Rear-Wheel Drive",
      acceleration: "5.6s 0-60 mph",
      top_speed: "155 mph",
      fuel_economy: "26 city / 36 highway mpg",
      weight: "3,582 lbs",
      cargo: "17 cu ft",
    },
  },
  {
    id: "3",
    name: "Toyota Camry",
    brand: "Toyota",
    price: 25945,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 28.7,
    power: 208,
    description:
      "The Toyota Camry is an automobile sold internationally by the Japanese manufacturer Toyota since 1982, spanning multiple generations. The Camry has been the best-selling passenger car in the United States.",
    specifications: {
      engine: "2.5L 4-Cylinder Hybrid",
      transmission: "CVT Automatic",
      drive: "Front-Wheel Drive",
      acceleration: "7.4s 0-60 mph",
      fuel_economy: "51 city / 53 highway mpg",
      weight: "3,480 lbs",
      cargo: "15.1 cu ft",
      warranty: "3-year/36,000-mile basic",
    },
  },
  {
    id: "4",
    name: "Honda CR-V",
    brand: "Honda",
    price: 26800,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 24.2,
    power: 190,
    description:
      "The Honda CR-V is a compact crossover SUV manufactured by Honda since 1995. It uses the Honda Civic platform with an SUV body design.",
    specifications: {
      engine: "1.5L 4-Cylinder Turbo",
      transmission: "CVT Automatic",
      drive: "All-Wheel Drive",
      acceleration: "7.5s 0-60 mph",
      fuel_economy: "28 city / 34 highway mpg",
      ground_clearance: "8.2 inches",
      cargo: "39.2 cu ft",
      towing: "1,500 lbs",
    },
  },
  {
    id: "5",
    name: "Ford Mustang",
    brand: "Ford",
    price: 27205,
    fuelType: "Petrol",
    seatingCapacity: 4,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 19.8,
    power: 310,
    description:
      "The Ford Mustang is a series of American automobiles manufactured by Ford. The Mustang is currently the longest-produced Ford car nameplate.",
    specifications: {
      engine: "2.3L 4-Cylinder EcoBoost",
      transmission: "6-Speed Manual",
      drive: "Rear-Wheel Drive",
      acceleration: "5.1s 0-60 mph",
      top_speed: "155 mph",
      fuel_economy: "21 city / 29 highway mpg",
      weight: "3,532 lbs",
      brakes: "4-wheel disc",
    },
  },
  {
    id: "6",
    name: "Audi Q5",
    brand: "Audi",
    price: 43500,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 22.5,
    power: 261,
    description:
      "The Audi Q5 is a series of compact luxury crossover SUVs produced by the German luxury car manufacturer Audi from 2008.",
    specifications: {
      engine: "2.0L 4-Cylinder Turbo",
      transmission: "7-Speed Dual-Clutch",
      drive: "All-Wheel Drive",
      acceleration: "5.7s 0-60 mph",
      top_speed: "130 mph",
      fuel_economy: "23 city / 28 highway mpg",
      weight: "4,079 lbs",
      cargo: "25.8 cu ft",
    },
  },
  {
    id: "7",
    name: "Mercedes-Benz C-Class",
    brand: "Mercedes-Benz",
    price: 43550,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 23.8,
    power: 255,
    description:
      "The Mercedes-Benz C-Class is a line of compact executive cars produced by Daimler AG. Introduced in 1993 as a replacement for the 190 range, the C-Class has been available with a 4MATIC option since 2002.",
    specifications: {
      engine: "2.0L 4-Cylinder Turbo",
      transmission: "9-Speed Automatic",
      drive: "Rear-Wheel Drive",
      acceleration: "5.9s 0-60 mph",
      top_speed: "130 mph",
      fuel_economy: "23 city / 35 highway mpg",
      weight: "3,693 lbs",
      safety: "5-star NHTSA rating",
    },
  },
  {
    id: "8",
    name: "Hyundai Tucson",
    brand: "Hyundai",
    price: 26450,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 29.4,
    power: 226,
    description:
      "The Hyundai Tucson is a compact crossover SUV produced by the South Korean manufacturer Hyundai since 2004. It is Hyundai's best-selling SUV globally.",
    specifications: {
      engine: "1.6L 4-Cylinder Turbo Hybrid",
      transmission: "6-Speed Automatic",
      drive: "All-Wheel Drive",
      acceleration: "7.1s 0-60 mph",
      fuel_economy: "38 city / 38 highway mpg",
      ground_clearance: "8.3 inches",
      cargo: "38.7 cu ft",
      warranty: "5-year/60,000-mile basic",
    },
  },
  {
    id: "9",
    name: "Chevrolet Silverado",
    brand: "Chevrolet",
    price: 35600,
    fuelType: "Petrol",
    seatingCapacity: 6,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 17.5,
    power: 355,
    description:
      "The Chevrolet Silverado is a range of trucks manufactured by General Motors under the Chevrolet brand. The Silverado range includes full-size pickup trucks, chassis cab trucks, and medium-duty trucks.",
    specifications: {
      engine: "5.3L V8",
      transmission: "10-Speed Automatic",
      drive: "Four-Wheel Drive",
      acceleration: "6.2s 0-60 mph",
      towing: "13,300 lbs",
      payload: "2,280 lbs",
      fuel_economy: "16 city / 20 highway mpg",
      bed_length: "6.6 ft",
    },
  },
  {
    id: "10",
    name: "Nissan Leaf",
    brand: "Nissan",
    price: 28040,
    fuelType: "Electric",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: "NA",
    power: 147,
    description:
      "The Nissan Leaf is a compact five-door hatchback battery electric vehicle manufactured by Nissan. It is one of the world's best-selling electric cars.",
    specifications: {
      range: "149-226 miles",
      battery: "40-62 kWh",
      charging: "Up to 50 kW DC fast charging",
      drive: "Front-Wheel Drive",
      acceleration: "7.4s 0-60 mph",
      top_speed: "90 mph",
      weight: "3,501 lbs",
      cargo: "23.6 cu ft",
    },
  },
  {
    id: "11",
    name: "Kia Sportage",
    brand: "Kia",
    price: 25990,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 25.6,
    power: 227,
    description:
      "The Kia Sportage is a compact crossover SUV manufactured by the South Korean manufacturer Kia since 1993. The Sportage has been Kia's best-selling model globally.",
    specifications: {
      engine: "1.6L 4-Cylinder Turbo Hybrid",
      transmission: "6-Speed Automatic",
      drive: "All-Wheel Drive",
      acceleration: "7.2s 0-60 mph",
      fuel_economy: "38 city / 38 highway mpg",
      ground_clearance: "8.3 inches",
      cargo: "39.5 cu ft",
      warranty: "5-year/60,000-mile basic",
    },
  },
  {
    id: "12",
    name: "Volvo XC60",
    brand: "Volvo",
    price: 43450,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 26.8,
    power: 400,
    description:
      "The Volvo XC60 is a compact luxury crossover SUV manufactured and marketed by Swedish automaker Volvo Cars. It is consistently one of Volvo's best-selling cars.",
    specifications: {
      engine: "2.0L 4-Cylinder Turbo Hybrid",
      transmission: "8-Speed Automatic",
      drive: "All-Wheel Drive",
      acceleration: "4.9s 0-60 mph",
      top_speed: "112 mph",
      fuel_economy: "26 city / 28 highway mpg",
      weight: "4,238 lbs",
      safety: "5-star Euro NCAP rating",
    },
  },
  {
    id: "13",
    name: "Jeep Wrangler",
    brand: "Jeep",
    price: 29995,
    fuelType: "Petrol",
    seatingCapacity: 4,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 17.7,
    power: 285,
    description:
      "The Jeep Wrangler is a series of compact and mid-size four-wheel drive off-road SUVs manufactured by Jeep since 1986, and currently in its fourth generation.",
    specifications: {
      engine: "3.6L V6",
      transmission: "8-Speed Automatic",
      drive: "Four-Wheel Drive",
      acceleration: "6.9s 0-60 mph",
      ground_clearance: "10.8 inches",
      water_fording: "30 inches",
      approach_angle: "44 degrees",
      departure_angle: "37 degrees",
    },
  },
  {
    id: "14",
    name: "Subaru Outback",
    brand: "Subaru",
    price: 28395,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 26.3,
    power: 182,
    description:
      "The Subaru Outback is a station wagon and crossover SUV manufactured by Subaru. It was first introduced in 1994 and is known for its standard all-wheel drive and boxer engine.",
    specifications: {
      engine: "2.5L 4-Cylinder Boxer",
      transmission: "CVT Automatic",
      drive: "All-Wheel Drive",
      acceleration: "8.7s 0-60 mph",
      ground_clearance: "8.7 inches",
      fuel_economy: "26 city / 33 highway mpg",
      cargo: "32.5 cu ft",
      towing: "2,700 lbs",
    },
  },
  {
    id: "15",
    name: "Mazda CX-5",
    brand: "Mazda",
    price: 26700,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 24.9,
    power: 187,
    description:
      "The Mazda CX-5 is a compact crossover SUV produced by Mazda starting in 2012. It is known for its engaging driving dynamics and upscale interior.",
    specifications: {
      engine: "2.5L 4-Cylinder",
      transmission: "6-Speed Automatic",
      drive: "All-Wheel Drive",
      acceleration: "8.2s 0-60 mph",
      fuel_economy: "24 city / 30 highway mpg",
      weight: "3,552 lbs",
      cargo: "30.9 cu ft",
      ground_clearance: "7.5 inches",
    },
  },
  {
    id: "16",
    name: "Lexus RX",
    brand: "Lexus",
    price: 46995,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 30.1,
    power: 308,
    description:
      "The Lexus RX is a luxury crossover SUV sold by Lexus, a luxury division of Toyota. Originally released as the Toyota Harrier in Japan in 1997, the RX has become one of Lexus's best-selling models.",
    specifications: {
      engine: "2.5L 4-Cylinder Hybrid",
      transmission: "CVT Automatic",
      drive: "All-Wheel Drive",
      acceleration: "7.0s 0-60 mph",
      fuel_economy: "31 city / 28 highway mpg",
      weight: "4,740 lbs",
      cargo: "29.6 cu ft",
      safety: "IIHS Top Safety Pick+",
    },
  },
  {
    id: "17",
    name: "Porsche 911",
    brand: "Porsche",
    price: 106100,
    fuelType: "Petrol",
    seatingCapacity: 4,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 18.0,
    power: 379,
    description:
      "The Porsche 911 is a two-door, 2+2 high performance rear-engined sports car introduced in September 1964 by Porsche AG of Stuttgart, Germany. It has a rear-mounted flat-six engine and all round independent suspension.",
    specifications: {
      engine: "3.0L Twin-Turbo Flat-6",
      transmission: "8-Speed PDK",
      drive: "Rear-Wheel Drive",
      acceleration: "3.7s 0-60 mph",
      top_speed: "182 mph",
      fuel_economy: "18 city / 24 highway mpg",
      weight: "3,354 lbs",
      brakes: "6-piston front, 4-piston rear",
    },
  },
  {
    id: "18",
    name: "Land Rover Defender",
    brand: "Land Rover",
    price: 53500,
    fuelType: "Petrol",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 17.2,
    power: 296,
    description:
      "The Land Rover Defender is a series of compact and mid-size four-wheel drive off-road SUVs, produced by Land Rover, now owned by Jaguar Land Rover.",
    specifications: {
      engine: "2.0L 4-Cylinder Turbo",
      transmission: "8-Speed Automatic",
      drive: "Four-Wheel Drive",
      acceleration: "7.0s 0-60 mph",
      ground_clearance: "11.5 inches",
      wading_depth: "35.4 inches",
      approach_angle: "38 degrees",
      payload: "1,984 lbs",
    },
  },
  {
    id: "19",
    name: "Volkswagen ID.4",
    brand: "Volkswagen",
    price: 37495,
    fuelType: "Electric",
    seatingCapacity: 5,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: "NA",
    power: 201,
    description:
      "The Volkswagen ID.4 is an all-electric compact crossover SUV produced by Volkswagen. It is the second model in the ID. series of Volkswagen electric vehicles.",
    specifications: {
      range: "275 miles",
      battery: "82 kWh",
      charging: "Up to 135 kW DC fast charging",
      drive: "Rear-Wheel Drive",
      acceleration: "7.6s 0-60 mph",
      top_speed: "99 mph",
      weight: "4,559 lbs",
      cargo: "30.3 cu ft",
    },
  },
  {
    id: "20",
    name: "Ferrari Roma",
    brand: "Ferrari",
    price: 222630,
    fuelType: "Petrol",
    seatingCapacity: 4,
    image: "/placeholder.svg?height=400&width=600",
    year: 2023,
    mileage: 17.9,
    power: 612,
    description:
      "The Ferrari Roma is a grand touring sports car produced by Italian automobile manufacturer Ferrari. The car is named after Italy's capital city, Rome.",
    specifications: {
      engine: "3.9L Twin-Turbo V8",
      transmission: "8-Speed Dual-Clutch",
      drive: "Rear-Wheel Drive",
      acceleration: "3.4s 0-60 mph",
      top_speed: "199 mph",
      fuel_economy: "17 city / 22 highway mpg",
      weight: "3,461 lbs",
      brakes: "Carbon ceramic",
    },
  },
]
